# Write DB
spring.datasource.write.url=jdbc:mysql://write-db:3306/app
spring.datasource.write.username=root
spring.datasource.write.password=password

# Read DB
spring.datasource.read.url=jdbc:mysql://read-db:3306/app
spring.datasource.read.username=root
spring.datasource.read.password=password