version: "3.7"
services:
  java:
    image: maven:3.8.6-openjdk-17   # Maven image with Java
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: this
    ports:
      - "3306:3306"